
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the lfa_PowerMgmtData_Configuration datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.lfa_PowerMgmtData_Configuration lfa_PowerMgmtData_Configuration
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.lfa_PowerMgmtData_Configuration);
            }
        }
        
        /// <summary>
        /// Gets the lfa_PowerMgmtData_Schedule datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.lfa_PowerMgmtData_Schedule lfa_PowerMgmtData_Schedule
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.lfa_PowerMgmtData_Schedule);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.lfa_PowerMgmtData_Configuration;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration> lfa_PowerMgmtData_Configuration
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.lfa_PowerMgmtData_Configuration) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule> lfa_PowerMgmtData_Schedule
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.lfa_PowerMgmtData_Schedule) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration>.Entry
                    lfa_PowerMgmtData_Configuration = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration>.Entry(
                        "lfa_PowerMgmtData_Configuration",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._lfa_PowerMgmtData_Configuration_Stub);
                private static void _lfa_PowerMgmtData_Configuration_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._lfa_PowerMgmtData_Configuration, sf);
                }
                 
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule>.Entry
                    lfa_PowerMgmtData_Schedule = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule>.Entry(
                        "lfa_PowerMgmtData_Schedule",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._lfa_PowerMgmtData_Schedule_Stub);
                private static void _lfa_PowerMgmtData_Schedule_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._lfa_PowerMgmtData_Schedule, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration>.Data _lfa_PowerMgmtData_Configuration;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule>.Data _lfa_PowerMgmtData_Schedule;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the lfa_PowerMgmtData_Configuration datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class lfa_PowerMgmtData_Configuration : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass>
    {
        #region Constructors
    
        public lfa_PowerMgmtData_Configuration() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Configuration_Devices entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Configuration_Device> Configuration_Devices
        {
            get
            {
                return global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.GetValue(this, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties.Configuration_Devices);
            }
        }
        
        /// <summary>
        /// Gets the Configuration_Unit entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Configuration_Unit> Configuration_Unit
        {
            get
            {
                return global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.GetValue(this, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties.Configuration_Unit);
            }
        }
        
        /// <summary>
        /// Gets the Configuration_Zones entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Configuration_Zone> Configuration_Zones
        {
            get
            {
                return global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.GetValue(this, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties.Configuration_Zones);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Configuration_Device Configuration_Devices_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Configuration_Devices_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Configuration_Device Configuration_Devices_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Configuration_Devices_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Configuration_Unit Configuration_Unit_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Configuration_Unit_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Configuration_Unit Configuration_Unit_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Configuration_Unit_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Configuration_Zone Configuration_Zones_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Configuration_Zones_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Configuration_Zone Configuration_Zones_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Configuration_Zones_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySet, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties.Configuration_Devices_Single;
                var initializePropertyEntry = global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties.Configuration_Devices;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device> Configuration_Devices_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties.Configuration_Devices_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device> Configuration_Devices_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties.Configuration_Devices_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit> Configuration_Unit_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties.Configuration_Unit_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit> Configuration_Unit_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties.Configuration_Unit_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone> Configuration_Zones_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties.Configuration_Zones_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone> Configuration_Zones_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties.Configuration_Zones_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device> Configuration_Devices
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties.Configuration_Devices) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit> Configuration_Unit
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties.Configuration_Unit) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone> Configuration_Zones
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties.Configuration_Zones) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Entry
                    Configuration_Devices_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Entry(
                        "Configuration_Devices_Single",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties._Configuration_Devices_Single_Stub);
                private static void _Configuration_Devices_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Devices_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Entry
                    Configuration_Devices_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Entry(
                        "Configuration_Devices_SingleOrDefault",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties._Configuration_Devices_SingleOrDefault_Stub);
                private static void _Configuration_Devices_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Devices_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Entry
                    Configuration_Unit_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Entry(
                        "Configuration_Unit_Single",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties._Configuration_Unit_Single_Stub);
                private static void _Configuration_Unit_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Unit_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Entry
                    Configuration_Unit_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Entry(
                        "Configuration_Unit_SingleOrDefault",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties._Configuration_Unit_SingleOrDefault_Stub);
                private static void _Configuration_Unit_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Unit_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Entry
                    Configuration_Zones_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Entry(
                        "Configuration_Zones_Single",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties._Configuration_Zones_Single_Stub);
                private static void _Configuration_Zones_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Zones_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Entry
                    Configuration_Zones_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Entry(
                        "Configuration_Zones_SingleOrDefault",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.MethodSetProperties._Configuration_Zones_SingleOrDefault_Stub);
                private static void _Configuration_Zones_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Zones_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Entry
                    Configuration_Devices = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Entry(
                        "Configuration_Devices",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties._Configuration_Devices_Stub);
                private static void _Configuration_Devices_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Devices, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Entry
                    Configuration_Unit = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Entry(
                        "Configuration_Unit",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties._Configuration_Unit_Stub);
                private static void _Configuration_Unit_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Unit, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Entry
                    Configuration_Zones = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Entry(
                        "Configuration_Zones",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass.PropertySetProperties._Configuration_Zones_Stub);
                private static void _Configuration_Zones_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Zones, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Data _Configuration_Devices;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Data _Configuration_Unit;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Data _Configuration_Zones;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Data _Configuration_Devices_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Device>.Data _Configuration_Devices_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Data _Configuration_Unit_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Data _Configuration_Unit_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Data _Configuration_Zones_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Configuration, global::LightSwitchApplication.lfa_PowerMgmtData_Configuration.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Data _Configuration_Zones_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// Provides members to query and update data in the lfa_PowerMgmtData_Schedule datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class lfa_PowerMgmtData_Schedule : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass>
    {
        #region Constructors
    
        public lfa_PowerMgmtData_Schedule() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Schedule_Device entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Schedule_Device> Schedule_Device
        {
            get
            {
                return global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties.Schedule_Device);
            }
        }
        
        /// <summary>
        /// Gets the Schedule_Schedule entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Schedule_Schedule> Schedule_Schedule
        {
            get
            {
                return global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties.Schedule_Schedule);
            }
        }
        
        /// <summary>
        /// Gets the Schedule_Unit entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Schedule_Unit> Schedule_Unit
        {
            get
            {
                return global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties.Schedule_Unit);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Schedule_Device Schedule_Device_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Schedule_Device_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Schedule_Device Schedule_Device_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Schedule_Device_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Schedule_Schedule Schedule_Schedule_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Schedule_Schedule_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Schedule_Schedule Schedule_Schedule_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Schedule_Schedule_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Schedule_Unit Schedule_Unit_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Schedule_Unit_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Schedule_Unit Schedule_Unit_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Schedule_Unit_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySet, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties.Schedule_Device_Single;
                var initializePropertyEntry = global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties.Schedule_Device;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device> Schedule_Device_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties.Schedule_Device_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device> Schedule_Device_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties.Schedule_Device_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule> Schedule_Schedule_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties.Schedule_Schedule_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule> Schedule_Schedule_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties.Schedule_Schedule_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit> Schedule_Unit_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties.Schedule_Unit_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit> Schedule_Unit_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties.Schedule_Unit_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device> Schedule_Device
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties.Schedule_Device) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule> Schedule_Schedule
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties.Schedule_Schedule) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit> Schedule_Unit
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties.Schedule_Unit) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Entry
                    Schedule_Device_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Entry(
                        "Schedule_Device_Single",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties._Schedule_Device_Single_Stub);
                private static void _Schedule_Device_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Device_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Entry
                    Schedule_Device_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Entry(
                        "Schedule_Device_SingleOrDefault",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties._Schedule_Device_SingleOrDefault_Stub);
                private static void _Schedule_Device_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Device_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Entry
                    Schedule_Schedule_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Entry(
                        "Schedule_Schedule_Single",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties._Schedule_Schedule_Single_Stub);
                private static void _Schedule_Schedule_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Schedule_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Entry
                    Schedule_Schedule_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Entry(
                        "Schedule_Schedule_SingleOrDefault",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties._Schedule_Schedule_SingleOrDefault_Stub);
                private static void _Schedule_Schedule_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Schedule_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Entry
                    Schedule_Unit_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Entry(
                        "Schedule_Unit_Single",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties._Schedule_Unit_Single_Stub);
                private static void _Schedule_Unit_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Unit_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Entry
                    Schedule_Unit_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Entry(
                        "Schedule_Unit_SingleOrDefault",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.MethodSetProperties._Schedule_Unit_SingleOrDefault_Stub);
                private static void _Schedule_Unit_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Unit_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Entry
                    Schedule_Device = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Entry(
                        "Schedule_Device",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties._Schedule_Device_Stub);
                private static void _Schedule_Device_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Device, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Entry
                    Schedule_Schedule = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Entry(
                        "Schedule_Schedule",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties._Schedule_Schedule_Stub);
                private static void _Schedule_Schedule_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Schedule, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Entry
                    Schedule_Unit = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Entry(
                        "Schedule_Unit",
                        global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass.PropertySetProperties._Schedule_Unit_Stub);
                private static void _Schedule_Unit_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Data> c, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Unit, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Data _Schedule_Device;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Data _Schedule_Schedule;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Data _Schedule_Unit;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Data _Schedule_Device_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Data _Schedule_Device_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Data _Schedule_Schedule_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Schedule>.Data _Schedule_Schedule_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Data _Schedule_Unit_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.lfa_PowerMgmtData_Schedule, global::LightSwitchApplication.lfa_PowerMgmtData_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Data _Schedule_Unit_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
