

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Configuration_Device : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Configuration_Device entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Configuration_Device()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Configuration_Device(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Configuration_Device> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Configuration_Device.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Configuration_Device_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Configuration_Device_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Configuration_Device.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Configuration_Device.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Configuration_Device.DetailsClass.SetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return global::LightSwitchApplication.Configuration_Device.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.DateAdded);
            }
            set
            {
                global::LightSwitchApplication.Configuration_Device.DetailsClass.SetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.DateAdded, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAdded_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAdded_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAdded_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool IsActive
        {
            get
            {
                return global::LightSwitchApplication.Configuration_Device.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.IsActive);
            }
            set
            {
                global::LightSwitchApplication.Configuration_Device.DetailsClass.SetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.IsActive, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Configuration_Unit Configuration_Unit
        {
            get
            {
                return global::LightSwitchApplication.Configuration_Device.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Configuration_Unit);
            }
            set
            {
                global::LightSwitchApplication.Configuration_Device.DetailsClass.SetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Configuration_Unit, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Configuration_Unit_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Configuration_Unit_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Configuration_Unit_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Schedule_Device> Schedule_Device
        {
            get
            {
                return global::LightSwitchApplication.Configuration_Device.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Schedule_Device);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Schedule_Device> Schedule_DeviceQuery
        {
            get
            {
                return global::LightSwitchApplication.Configuration_Device.DetailsClass.GetQuery(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Schedule_Device);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Configuration_Zone Zone
        {
            get
            {
                return global::LightSwitchApplication.Configuration_Device.DetailsClass.GetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Zone);
            }
            set
            {
                global::LightSwitchApplication.Configuration_Device.DetailsClass.SetValue(this, global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Zone, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zone_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zone_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Zone_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Configuration_Device,
                global::LightSwitchApplication.Configuration_Device.DetailsClass,
                global::LightSwitchApplication.Configuration_Device.DetailsClass.IImplementation,
                global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass>.Entry
                __Configuration_DeviceEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass>.Entry(
                    global::LightSwitchApplication.Configuration_Device.DetailsClass.__Configuration_Device_CreateNew,
                    global::LightSwitchApplication.Configuration_Device.DetailsClass.__Configuration_Device_Created,
                    global::LightSwitchApplication.Configuration_Device.DetailsClass.__Configuration_Device_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Configuration_Device __Configuration_Device_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Configuration_Device> es)
            {
                return new global::LightSwitchApplication.Configuration_Device(es);
            }
            private static void __Configuration_Device_Created(global::LightSwitchApplication.Configuration_Device e)
            {
                e.Configuration_Device_Created();
            }
            private static bool __Configuration_Device_AllowSaveWithErrors(global::LightSwitchApplication.Configuration_Device e)
            {
                bool result = false;
                e.Configuration_Device_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::System.DateTime> DateAdded
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.DateAdded) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, bool> IsActive
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.IsActive) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, bool>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Unit> Configuration_Unit
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Configuration_Unit) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Unit>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Schedule_Device> Schedule_Device
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Schedule_Device) as global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Schedule_Device>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Zone> Zone
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Zone) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Zone>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new global::System.DateTime DateAdded { get; set; }
                new bool IsActive { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Configuration_Unit { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Zone { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration_Device.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, int>.Data> c, global::LightSwitchApplication.Configuration_Device.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Configuration_Device e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Configuration_Device e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Configuration_Device e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration_Device.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, string>.Data> c, global::LightSwitchApplication.Configuration_Device.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Configuration_Device e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Configuration_Device e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Configuration_Device e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::System.DateTime>.Entry
                    DateAdded = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::System.DateTime>.Entry(
                        "DateAdded",
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._DateAdded_Stub,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._DateAdded_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._DateAdded_Validate,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._DateAdded_GetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._DateAdded_SetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._DateAdded_OnValueChanged);
                private static void _DateAdded_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration_Device.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Configuration_Device.DetailsClass d, object sf)
                {
                    c(d, ref d._DateAdded, sf);
                }
                private static bool _DateAdded_ComputeIsReadOnly(global::LightSwitchApplication.Configuration_Device e)
                {
                    bool result = false;
                    e.DateAdded_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateAdded_Validate(global::LightSwitchApplication.Configuration_Device e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateAdded_Validate(r);
                }
                private static global::System.DateTime _DateAdded_GetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    return d.ImplementationEntity.DateAdded;
                }
                private static void _DateAdded_SetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateAdded = global::LightSwitchApplication.Configuration_Device.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _DateAdded_OnValueChanged(global::LightSwitchApplication.Configuration_Device e)
                {
                    e.DateAdded_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, bool>.Entry
                    IsActive = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, bool>.Entry(
                        "IsActive",
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._IsActive_Stub,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._IsActive_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._IsActive_Validate,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._IsActive_GetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._IsActive_SetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._IsActive_OnValueChanged);
                private static void _IsActive_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration_Device.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, bool>.Data> c, global::LightSwitchApplication.Configuration_Device.DetailsClass d, object sf)
                {
                    c(d, ref d._IsActive, sf);
                }
                private static bool _IsActive_ComputeIsReadOnly(global::LightSwitchApplication.Configuration_Device e)
                {
                    bool result = false;
                    e.IsActive_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsActive_Validate(global::LightSwitchApplication.Configuration_Device e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsActive_Validate(r);
                }
                private static bool _IsActive_GetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    return d.ImplementationEntity.IsActive;
                }
                private static void _IsActive_SetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d, bool v)
                {
                    d.ImplementationEntity.IsActive = v;
                }
                private static void _IsActive_OnValueChanged(global::LightSwitchApplication.Configuration_Device e)
                {
                    e.IsActive_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Entry
                    Configuration_Unit = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Entry(
                        "Configuration_Unit",
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Configuration_Unit_Stub,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Configuration_Unit_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Configuration_Unit_Validate,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Configuration_Unit_GetCoreImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Configuration_Unit_GetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Configuration_Unit_SetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Configuration_Unit_Refresh,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Configuration_Unit_OnValueChanged);
                private static void _Configuration_Unit_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration_Device.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Data> c, global::LightSwitchApplication.Configuration_Device.DetailsClass d, object sf)
                {
                    c(d, ref d._Configuration_Unit, sf);
                }
                private static bool _Configuration_Unit_ComputeIsReadOnly(global::LightSwitchApplication.Configuration_Device e)
                {
                    bool result = false;
                    e.Configuration_Unit_IsReadOnly(ref result);
                    return result;
                }
                private static void _Configuration_Unit_Validate(global::LightSwitchApplication.Configuration_Device e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Configuration_Unit_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Configuration_Unit_GetCoreImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    return d.ImplementationEntity.Configuration_Unit;
                }
                private static global::LightSwitchApplication.Configuration_Unit _Configuration_Unit_GetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Configuration_Unit, global::LightSwitchApplication.Configuration_Unit.DetailsClass>(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Configuration_Unit, ref d._Configuration_Unit);
                }
                private static void _Configuration_Unit_SetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d, global::LightSwitchApplication.Configuration_Unit v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Configuration_Unit, ref d._Configuration_Unit, (i, ev) => i.Configuration_Unit = ev, v);
                }
                private static void _Configuration_Unit_Refresh(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Configuration_Unit, ref d._Configuration_Unit);
                }
                private static void _Configuration_Unit_OnValueChanged(global::LightSwitchApplication.Configuration_Device e)
                {
                    e.Configuration_Unit_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Entry
                    Schedule_Device = new global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Entry(
                        "Schedule_Device",
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Schedule_Device_Stub);
                private static void _Schedule_Device_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration_Device.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Data> c, global::LightSwitchApplication.Configuration_Device.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Device, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Entry
                    Zone = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Entry(
                        "Zone",
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Zone_Stub,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Zone_ComputeIsReadOnly,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Zone_Validate,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Zone_GetCoreImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Zone_GetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Zone_SetImplementationValue,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Zone_Refresh,
                        global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties._Zone_OnValueChanged);
                private static void _Zone_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Configuration_Device.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Data> c, global::LightSwitchApplication.Configuration_Device.DetailsClass d, object sf)
                {
                    c(d, ref d._Zone, sf);
                }
                private static bool _Zone_ComputeIsReadOnly(global::LightSwitchApplication.Configuration_Device e)
                {
                    bool result = false;
                    e.Zone_IsReadOnly(ref result);
                    return result;
                }
                private static void _Zone_Validate(global::LightSwitchApplication.Configuration_Device e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Zone_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Zone_GetCoreImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    return d.ImplementationEntity.Zone;
                }
                private static global::LightSwitchApplication.Configuration_Zone _Zone_GetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Configuration_Zone, global::LightSwitchApplication.Configuration_Zone.DetailsClass>(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Zone, ref d._Zone);
                }
                private static void _Zone_SetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass d, global::LightSwitchApplication.Configuration_Zone v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Zone, ref d._Zone, (i, ev) => i.Zone = ev, v);
                }
                private static void _Zone_Refresh(global::LightSwitchApplication.Configuration_Device.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Configuration_Device.DetailsClass.PropertySetProperties.Zone, ref d._Zone);
                }
                private static void _Zone_OnValueChanged(global::LightSwitchApplication.Configuration_Device e)
                {
                    e.Zone_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::System.DateTime>.Data _DateAdded;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, bool>.Data _IsActive;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Unit>.Data _Configuration_Unit;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityVirtualCollectionProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Schedule_Device>.Data _Schedule_Device;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Configuration_Device, global::LightSwitchApplication.Configuration_Device.DetailsClass, global::LightSwitchApplication.Configuration_Zone>.Data _Zone;
            
        }
    
        #endregion
    }
    
    #endregion
}
