

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Schedule_Schedule : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Schedule_Schedule entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Schedule_Schedule()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Schedule_Schedule(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Schedule_Schedule> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Schedule_Schedule.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Schedule_Schedule_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Schedule_Schedule_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass.SetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string StartTime
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.StartTime);
            }
            set
            {
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass.SetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.StartTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void StartTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string EndTime
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.EndTime);
            }
            set
            {
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass.SetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.EndTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EndTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EndTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EndTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ElapseTime
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.ElapseTime);
            }
            set
            {
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass.SetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.ElapseTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ElapseTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ElapseTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ElapseTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.DateAdded);
            }
            set
            {
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass.SetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.DateAdded, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAdded_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAdded_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DateAdded_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<bool> IsActive
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.IsActive);
            }
            set
            {
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass.SetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.IsActive, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void IsActive_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Schedule_Unit> Schedule_Unit
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetValue(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Schedule_Unit);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Schedule_Unit> Schedule_UnitQuery
        {
            get
            {
                return global::LightSwitchApplication.Schedule_Schedule.DetailsClass.GetQuery(this, global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Schedule_Unit);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Schedule_Schedule,
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass,
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass.IImplementation,
                global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass>.Entry
                __Schedule_ScheduleEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass>.Entry(
                    global::LightSwitchApplication.Schedule_Schedule.DetailsClass.__Schedule_Schedule_CreateNew,
                    global::LightSwitchApplication.Schedule_Schedule.DetailsClass.__Schedule_Schedule_Created,
                    global::LightSwitchApplication.Schedule_Schedule.DetailsClass.__Schedule_Schedule_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Schedule_Schedule __Schedule_Schedule_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Schedule_Schedule> es)
            {
                return new global::LightSwitchApplication.Schedule_Schedule(es);
            }
            private static void __Schedule_Schedule_Created(global::LightSwitchApplication.Schedule_Schedule e)
            {
                e.Schedule_Schedule_Created();
            }
            private static bool __Schedule_Schedule_AllowSaveWithErrors(global::LightSwitchApplication.Schedule_Schedule e)
            {
                bool result = false;
                e.Schedule_Schedule_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string> StartTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.StartTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string> EndTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.EndTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int> ElapseTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.ElapseTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.DateTime> DateAdded
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.DateAdded) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.Nullable<bool>> IsActive
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.IsActive) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.Nullable<bool>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit> Schedule_Unit
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Schedule_Unit) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string Name { get; set; }
                new string StartTime { get; set; }
                new string EndTime { get; set; }
                new int ElapseTime { get; set; }
                new global::System.DateTime DateAdded { get; set; }
                new global::System.Nullable<bool> IsActive { get; set; }
                new global::System.Collections.IEnumerable Schedule_Unit { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>.Data> c, global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Schedule_Schedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Data> c, global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.Schedule_Schedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Entry
                    StartTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Entry(
                        "StartTime",
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._StartTime_Stub,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._StartTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._StartTime_Validate,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._StartTime_GetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._StartTime_SetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._StartTime_OnValueChanged);
                private static void _StartTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Data> c, global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._StartTime, sf);
                }
                private static bool _StartTime_ComputeIsReadOnly(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    bool result = false;
                    e.StartTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _StartTime_Validate(global::LightSwitchApplication.Schedule_Schedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.StartTime_Validate(r);
                }
                private static string _StartTime_GetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.ImplementationEntity.StartTime;
                }
                private static void _StartTime_SetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, string v)
                {
                    d.ImplementationEntity.StartTime = v;
                }
                private static void _StartTime_OnValueChanged(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    e.StartTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Entry
                    EndTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Entry(
                        "EndTime",
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._EndTime_Stub,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._EndTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._EndTime_Validate,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._EndTime_GetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._EndTime_SetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._EndTime_OnValueChanged);
                private static void _EndTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Data> c, global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._EndTime, sf);
                }
                private static bool _EndTime_ComputeIsReadOnly(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    bool result = false;
                    e.EndTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _EndTime_Validate(global::LightSwitchApplication.Schedule_Schedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.EndTime_Validate(r);
                }
                private static string _EndTime_GetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.ImplementationEntity.EndTime;
                }
                private static void _EndTime_SetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, string v)
                {
                    d.ImplementationEntity.EndTime = v;
                }
                private static void _EndTime_OnValueChanged(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    e.EndTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>.Entry
                    ElapseTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>.Entry(
                        "ElapseTime",
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._ElapseTime_Stub,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._ElapseTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._ElapseTime_Validate,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._ElapseTime_GetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._ElapseTime_SetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._ElapseTime_OnValueChanged);
                private static void _ElapseTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>.Data> c, global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._ElapseTime, sf);
                }
                private static bool _ElapseTime_ComputeIsReadOnly(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    bool result = false;
                    e.ElapseTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _ElapseTime_Validate(global::LightSwitchApplication.Schedule_Schedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ElapseTime_Validate(r);
                }
                private static int _ElapseTime_GetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.ImplementationEntity.ElapseTime;
                }
                private static void _ElapseTime_SetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ElapseTime = v;
                }
                private static void _ElapseTime_OnValueChanged(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    e.ElapseTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.DateTime>.Entry
                    DateAdded = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.DateTime>.Entry(
                        "DateAdded",
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._DateAdded_Stub,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._DateAdded_ComputeIsReadOnly,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._DateAdded_Validate,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._DateAdded_GetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._DateAdded_SetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._DateAdded_OnValueChanged);
                private static void _DateAdded_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._DateAdded, sf);
                }
                private static bool _DateAdded_ComputeIsReadOnly(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    bool result = false;
                    e.DateAdded_IsReadOnly(ref result);
                    return result;
                }
                private static void _DateAdded_Validate(global::LightSwitchApplication.Schedule_Schedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DateAdded_Validate(r);
                }
                private static global::System.DateTime _DateAdded_GetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.ImplementationEntity.DateAdded;
                }
                private static void _DateAdded_SetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.DateAdded = global::LightSwitchApplication.Schedule_Schedule.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _DateAdded_OnValueChanged(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    e.DateAdded_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.Nullable<bool>>.Entry
                    IsActive = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.Nullable<bool>>.Entry(
                        "IsActive",
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._IsActive_Stub,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._IsActive_ComputeIsReadOnly,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._IsActive_Validate,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._IsActive_GetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._IsActive_SetImplementationValue,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._IsActive_OnValueChanged);
                private static void _IsActive_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.Nullable<bool>>.Data> c, global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._IsActive, sf);
                }
                private static bool _IsActive_ComputeIsReadOnly(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    bool result = false;
                    e.IsActive_IsReadOnly(ref result);
                    return result;
                }
                private static void _IsActive_Validate(global::LightSwitchApplication.Schedule_Schedule e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.IsActive_Validate(r);
                }
                private static global::System.Nullable<bool> _IsActive_GetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.ImplementationEntity.IsActive;
                }
                private static void _IsActive_SetImplementationValue(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, global::System.Nullable<bool> v)
                {
                    d.ImplementationEntity.IsActive = v;
                }
                private static void _IsActive_OnValueChanged(global::LightSwitchApplication.Schedule_Schedule e)
                {
                    e.IsActive_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Entry
                    Schedule_Unit = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Entry(
                        "Schedule_Unit",
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Schedule_Unit_Stub,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Schedule_Unit_GetReferencedEntities,
                        global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties._Schedule_Unit_GetEntityCollection);
                private static void _Schedule_Unit_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Data> c, global::LightSwitchApplication.Schedule_Schedule.DetailsClass d, object sf)
                {
                    c(d, ref d._Schedule_Unit, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Schedule_Unit> _Schedule_Unit_GetReferencedEntities(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Schedule_Unit, global::LightSwitchApplication.Schedule_Unit.DetailsClass>(global::LightSwitchApplication.Schedule_Schedule.DetailsClass.PropertySetProperties.Schedule_Unit, ref d._Schedule_Unit);
                }
                private static global::System.Collections.IEnumerable _Schedule_Unit_GetEntityCollection(global::LightSwitchApplication.Schedule_Schedule.DetailsClass d)
                {
                    return d.ImplementationEntity.Schedule_Unit;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Data _StartTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, string>.Data _EndTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, int>.Data _ElapseTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.DateTime>.Data _DateAdded;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::System.Nullable<bool>>.Data _IsActive;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Schedule_Schedule, global::LightSwitchApplication.Schedule_Schedule.DetailsClass, global::LightSwitchApplication.Schedule_Unit>.Data _Schedule_Unit;
            
        }
    
        #endregion
    }
    
    #endregion
}
